name: Code Embedder

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  code_embedder:
    name: "Code embedder"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}


      - name: Run code embedder
        uses: kvankova/code-embedder@v0.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.CODE_EMBEDDER }}
